### ISSUE TITLE
allow custom hostnames

### ISSUE THREAD

**Issue by es128** [paulmillr/pushserve#8]
Allow the user to set the IP/hostname the server should listen on instead of always using node's default.

https://github.com/brunch/brunch/issues/929

**Comment by bradobro** [comment]
@paulmillr I'm finding I need this to collaborate with a new remote worker on platforms such as Nitrous.io and c9.io--they want the server bound to a different port.

I could write a custom server, but I'd probably just copy and paste pushserve so I don't have to rewrite the pushstate stuff.

If I make a PR to allow, say `-b --bind`, to specify a hostname, would you consider it?

**Comment by paulmillr** [comment]
why not -h?

**Comment by bradobro** [comment]
Okay by me, but it's often used for --help (even by brunch). Your call...

**Comment by bradobro** [comment]
nvm, looks looks like @yavorsky added this in 4540da01b218649e699e819f5110d9516b691812, I'll PR the readme.

**Comment by bradobro** [comment]
Thanks @paulmillr could you release 1.6.1 to npm so the hostname prints out correctly in brunch (cf. brunch/brunch#929)
